- app/helpers/frontend/application_helper.rb
the definition of the variabels
> This is the second pull out of 2 to include diaspora on the sharing page of the video player

- .gitignore
- README.md
- test/fixtures/conferences.yml
- test/fixtures/events.yml
- test/fixtures/news.yml
- test/fixtures/recordings.yml
Commands to get your own media.ccc.de instance up an running as quick as possible.
> Add Quickstart-Guide to README

- app/views/frontend/home/about.haml
The App ist released and ready for download.
> Changed information about the AppleTV App

- app/views/frontend/conferences/show.html.haml
> title as h1, slug as h2 if necessary

- app/assets/javascripts/application.js
- app/assets/javascripts/jquery.bxslider.js
- app/assets/javascripts/jquery.nextPrevWrap.js
- app/assets/javascripts/slider.js
- app/assets/stylesheets/application.css
- app/assets/stylesheets/frontend/styles.scss
- app/assets/stylesheets/jquery.bxslider.css
- app/views/frontend/shared/_promoted.haml
> upgrade to a slider which shows multiple items in an carousel, fixes #72

- app/views/frontend/events/show.html.haml
- app/views/frontend/recent_changes/index.haml
- app/views/frontend/shared/_event_persons.haml
> Fix fontawsome wrapping of Text

- app/assets/stylesheets/frontend/styles.scss
> fix mobile-buttons in header

- app/assets/stylesheets/frontend/styles.scss
> up max-width to 1000px

- app/assets/stylesheets/frontend/styles.scss
> fix promoted slider on mobile devices

- app/models/frontend/recording.rb
- app/views/frontend/shared/_videoplayer.haml
- config/settings.yml.template
> use vhost with cors header for subtitles

- app/models/recording.rb
- lib/languages.rb
- test/models/recording_test.rb
> add minimal required languages for subtitles + longform

- app/controllers/api/events_controller.rb
- app/controllers/public/events_controller.rb
- config/routes.rb
- test/controllers/public/events_controller_test.rb
> Public + Private API: Allow event lookup via uuid

- .travis.yml
- Gemfile
- Gemfile.lock
- Vagrantfile
- app/admin/conference.rb
- app/admin/event.rb
- app/admin/recording.rb
- app/controllers/api/conferences_controller.rb
- app/models/concerns/elasticsearch_event.rb
- app/models/event.rb
- app/models/frontend/event.rb
- app/models/recording.rb
- app/views/frontend/events/show.html.haml
- app/views/frontend/home/about.haml
- bin/setup
- config/database.yml.template
- db/migrate/20160827151338_add_metadata_to_conference.rb
- db/schema.rb
This would make postgresql a hard requirement, because of 4db6650
We already require elasticsearch and redis.
> Saturday Session

- app/models/conference.rb
- app/models/event.rb
- app/models/recording.rb
- test/models/conference_test.rb
- test/models/event_test.rb
- test/models/recording_test.rb
fixes #120 
@manno would you mind reviewing this?
> trim paths in backend & api

- app/assets/stylesheets/frontend/styles.scss
- app/views/frontend/tags/show.html.haml
> use the event-partitial to unify tags-layout and browser-layout

- app/views/frontend/shared/_event_metadata.haml
> change event-metadata partitial to make thumbnail clickable again

- app/models/concerns/elasticsearch_event.rb
> add slug to elasticsearch serializer

- app/controllers/frontend/search_controller.rb
- app/views/frontend/search/index.html.haml
- app/views/frontend/shared/_navbar.haml
> display the searchquery on the search-result-page

- app/assets/javascripts/slider.js
see http://stackoverflow.com/a/18770589
fixes #116
> repair karussell for turblinks5

- Vagrantfile
fixes #132 
just depending / waiting for the mount doesn't seem to be enough, so keep retrying after the mount showed up.
> fix puma start in vagrant

- app/assets/javascripts/slider.js
fixes #116 this time maybe completely :/
> 116 repair karussell turbolinks5, try2

- app/assets/stylesheets/frontend/shared/_videoplayer.scss
> fix fullscreen player-placement

- app/assets/stylesheets/frontend/pages/_list.scss
- app/assets/stylesheets/frontend/pages/_start.scss
to be merged when the images are finally re-integrated
(tested with the existing _new images)
> support danymic sized images

- app/assets/stylesheets/frontend/pages/_show.scss
- app/models/frontend/recording.rb
- app/views/frontend/shared/_download.haml
> add torrent-buttons to download-links

- app/models/conference.rb
- app/models/event.rb
- app/models/recording.rb
> Fix downloaded event count

- app/views/frontend/shared/_videoplayer.haml
my guess related to #48 
I think we have to deploy the change to test if it actually fixes the problem – I currently can not think of another way to test this...
> subtitles: fix cross origin error

- app/views/frontend/shared/_navbar.haml
- config/locales/custom.en.yml
> Unify "C3TV" and "ccc-tv" to "media.ccc.de"

- app/controllers/frontend/home_controller.rb
- app/views/frontend/home/index.html.haml
> Show sum of events' durations on the frontpage

- .gitignore
- app/assets/javascripts/application.js
- app/assets/javascripts/feed_toggle.js
- app/assets/stylesheets/frontend/base/_feeds_dropdown.scss
- app/assets/stylesheets/frontend/base/_navbar.scss
- app/assets/stylesheets/frontend/styles.scss
- app/controllers/frontend/feeds_controller.rb
- app/controllers/frontend/news_controller.rb
- app/helpers/frontend/event_recording_filter.rb
- app/helpers/frontend/event_recording_filter_high_quality.rb
- app/helpers/frontend/event_recording_filter_low_quality.rb
- app/helpers/frontend/feed_quality.rb
- app/helpers/frontend/feeds_navigation_bar_structure_helper.rb
- app/models/frontend/event.rb
- app/models/news.rb
- app/models/recording.rb
- app/views/frontend/shared/_folder_feeds.haml
- app/views/frontend/shared/_navbar.haml
- app/views/frontend/shared/_navbar_feeds.haml
- app/views/frontend/shared/_navbar_folder_feeds.haml
- config/routes.rb
- lib/feeds/podcast_generator.rb
- lib/mime_type.rb
- test/controllers/frontend/feeds_controller_test.rb
Fixes  #201
Feed dropdown is now built up dynamically by abstract datastructure.
Ignore IntelliJ .idea dir and .iml
Added tests for round_time method and clarified its purpose by name
Old feeds are still available and untouched - I compared the result with the live version.
>  #201 Added SD podcast stream option. Added responsive feed dropdown menu.

- app/models/concerns/elasticsearch_event.rb
> use days as unit is decay-filter

- app/views/frontend/home/about.haml
Kodi changed their home page layout and nobody noticed ;)
> Fix Kodi link (and unify the rest of the list).

- app/assets/stylesheets/embed.css.scss
- app/helpers/frontend/application_helper.rb
- app/views/layouts/frontend/oembed.html.haml
- app/views/public/_html5player.html.erb
- config/initializers/assets.rb
- config/settings.yml.template
Try to make OEmbed a bit more usable:
- Remove setting and let Rails calculate the URL
- Let the player always fill the complete iframe
I hope this doesn't make it worse :P
> OEmbed fixes (fixes #259)

- app/controllers/public/conferences_controller.rb
- test/controllers/public/conferences_controller_test.rb
> public API: add /public/conferences/:acronym

- bin/update-data
- lib/tasks/db_load_fixtures_with_jsonb.rake
> cleanup received demo-data for a working dev-env

- app/admin/event.rb
- app/helpers/frontend/application_helper.rb
- app/models/frontend/event.rb
- app/models/recording.rb
- app/views/frontend/shared/_download.haml
- lib/mime_type.rb
- test/models/frontend/event_test.rb
- test/models/recording_test.rb
This PR provides basic support to add lecure slides as PDF or (MP4) video to an event.
> Optimize Download section + add slides

- app/views/frontend/shared/_short_about.haml
Regards and a smooth start into 2018! :)
Have fun at the conference!
> fixed small spelling mistake

- app/views/frontend/home/about.haml
add link and short description for c3vocupdater plugin for dreambox set-top-boxes
> add c3vocupdater plugin

- app/views/frontend/home/about.haml
> fixed link

- .dockerignore
- Dockerfile
- Gemfile
- README.md
- config/database.yml.docker
- docker-compose.yml
This setup uses docker-compose and the official ruby, postgres,
elasticsearch, and redis images. The README describes how to set up a
development environment, this replaces the old Vagrant setup.
> Basic Docker containerization for development

- app/views/frontend/home/index.html.haml
> Add button for old hierarchical browsing interface on startpage

- lib/languages.rb
> Add chinese language codes

- lib/languages.rb
> Add arabic language code

- app/views/frontend/home/about.haml
I build a quick and dirty integration for LG WebOS 
App store approval is still pending
> added LG WebOS app

- app/views/frontend/home/about.haml
Add NewPipe to list of supported media.ccc apps
> Add NewPipe to list of supported media.ccc apps

- app/controllers/frontend/home_controller.rb
- app/views/frontend/home/index_klimastreik.html.haml
Vorschlag für den globalen Klimastreik am 20.09.:
- wir liefern auf der Startseite eine Liste von Talks die sich mit Klima und Nachhaltigkeit beschäftigen
- Auslieferung der Seite ist auf dem 20.09. beschränkt
- iframe-Includes oder externe Links sind nicht betroffen und können weiterhin erreicht werden
- wenn man auf der Seite ganz nach unten scrollt kann man weiterhin Media wie gewohnt verwenden
> overwrite home with climate related talks on 20.09.

- app/assets/stylesheets/frontend/shared/_videoplayer.scss
- app/controllers/frontend/events_controller.rb
- app/views/frontend/events/show.html.haml
- app/views/frontend/shared/_player_video.haml
- app/views/frontend/shared/_player_video_native.haml
Related/preperation for #264 and #351
> Add option to test other players via GET parameter

- app/admin/event.rb
- app/controllers/api/events_controller.rb
- app/models/event.rb
- app/views/frontend/events/show.html.haml
- db/migrate/20190928125825_add_doi_to_events.rb
- db/schema.rb
pull request implementing #232 
* added doi to event model
* added link in metadata section under event
* includes doi validation
> Events doi #232

- app/views/frontend/events/playlist.html.haml
- vendor/assets/stylesheets/timelens.css
> Move timelens below player on narrow screens

- app/helpers/frontend/application_helper.rb
- app/views/frontend/events/show.html.haml
* remove googleplus code
* better cache key
* replace event.link label with 'Fahrplan'
> Smaller fixes after discussion, e.g. caching

- app/controllers/api/conferences_controller.rb
- app/controllers/api/events_controller.rb
- app/controllers/api/recordings_controller.rb
- app/controllers/application_controller.rb
- app/controllers/concerns/api_error_responses.rb
for more information on that topic, see e.g. https://www.pluralsight.com/blog/tutorials/token-based-authentication-rails
> API: authorisation via header and better error responeses

- app/assets/stylesheets/frontend/shared/_promoted.scss
- app/controllers/frontend/home_controller.rb
- app/models/frontend/conference.rb
- app/views/frontend/shared/_live.html.haml
this will add conference title for multiple live events
> title for multiple live conferences

- app/assets/stylesheets/jquery.bxslider.css.scss
> Fixed missing slideshow dot by removing unnecessary CSS segment

- lib/languages.rb
https://iso639-3.sil.org/code/swg
https://en.wikipedia.org/wiki/Swabian_German
https://de.wikipedia.org/wiki/Alemannische_Dialekte
> add swabian language code

- Gemfile
- Gemfile.lock
- app/graphql/media_backend_schema.rb
- app/graphql/resolvers/conference.rb
- app/graphql/schema.graphql
- app/graphql/types/asset_type.rb
- app/graphql/types/conference_type.rb
- app/graphql/types/date_time_type.rb
- app/graphql/types/lecture_type.rb
- app/graphql/types/query_type.rb
- app/graphql/types/url_type.rb
- app/models/event.rb
- app/models/frontend/event.rb
- config/initializers/cors_public.rb
- config/initializers/graphql.rb
- run_tests_graphql.sh
- test/integration/graphql/conferences_test.rb
- test/integration/graphql/schema_test.rb
based on work from @barnslig in https://github.com/barnslig/mediacccde-graphql/blob/master/src/schema.graphql
> GraphQL: add more attributes

- vendor/assets/stylesheets/timelens.css
> Prevent Timelens thumbnail from triggering hover events

- Gemfile
- Gemfile.lock
- app/assets/config/manifest.js
- app/models/concerns/elasticsearch_event.rb
> Upgrade deps, Versuch 2

- Gemfile
- Gemfile.lock
- app/assets/config/manifest.js
- app/controllers/graphql_controller.rb
- app/graphql/types/asset_type.rb
- app/graphql/types/conference_type.rb
- app/graphql/types/lecture_type.rb
- app/graphql/types/query_type.rb
- test/integration/graphql/lecture_test.rb
- test/test_helper.rb
fixes #471 (see second comment)
> GraphQL API fixes

- README.md
See https://api.media.ccc.de/public/events/recent
Related commit d4140e6bb2beb9ed6eac2166d98d09c206117e2a
> Add /public/events/recent API endpoint to README

- app/graphql/types/query_type.rb
- test/integration/graphql/conferences_test.rb
Hi,
I tried my luck with a fix for one of the queries mentioned in https://github.com/voc/voctoweb/issues/510 and copied one of the already present tests to work with said query.
Reference for the prepare context: https://graphql-ruby.org/fields/arguments.html
> Fix conferencesRecent graphql query

- Dockerfile
bba25abde8db530e64e24f2bbfeaafc7ddfbe965
> Add optimizations back

- Vagrantfile
* media.ccc.vm not working on Mac: issue with private network
* installed ruby version doesn't match `.ruby-version`, since worktree is not mounted during provisioning
* switch to RVM single  user, no need to install globally and `chown vagrant /usr/local/rvm/gems`
> Vagrant update

- app/views/frontend/home/about.haml
[media.ccc.de](https://media.ccc.de) media library application for webOS..
> App submission: CCCBib for WebOS

- app/views/frontend/home/about.haml
I built it yesterday and it has been merged.
Related: https://github.com/miru-project/repo/pull/325
> Mention Miru media.ccc.de extension
