app/assets/javascripts/search.js
Fix for #6. Although I think this could be fixed better in the Perl-Script (due to the lack of Date-Formatting mechanics in Javascript), I'm not a Perl-Guy so I fixed it in the JS.
=> hide date if null and format if not

app/assets/javascripts/application.js, app/assets/javascripts/mirrorbrain-fix.js, app/assets/javascripts/replacehash.js, app/views/frontend/events/show.html.haml
ensuring that the history state is never null fixes the turbolinks errors.
fixes #36
=> shim window.location.replaceHash and use it in all places

app/assets/javascripts/mirrorbrain-fix.js
since all web-videoplayers i know have the fullscreen button on the lower right corner, do so here, too. Since speed and sourcechooser are pretty wide, the fullscreen button was shifted pretty far away from the corner.
=> Player: fullscreen feature to the right

app/assets/stylesheets/frontend/_videoplayer.scss
fixes #125 
before:
after:
(the full-site image links to one of the available video-files)
=> style player-error page

lib/tasks/db_dump_fixtures.rake
regarding #111 
change the default so that only public data is dumped, when `rake db:fixtures:dump` is invoked.
To also dump private data, call `db:fixtures:dump[true]`.
=> skip tables with private content unless requested explicitly

README.md, Vagrantfile
Small improvements from my first time setup experience using vagrant. Please consider integration.
The hostname is setup by the vagrant-hostupdater and localhost is not correct. I think proper VM names help when you are using the virtualbox UI. Exiting vagrant boxes are renamed seamlessly.
=> First time setup fixes

app/controllers/concerns/throttle_connections.rb, app/controllers/public/events_controller.rb, app/controllers/public/recordings_controller.rb, app/models/recording_view.rb, db/migrate/20170103122951_add_identifiers_to_recording_views.rb, db/schema.rb
Store user agent and hashed IP address on recording views.
The IP is hashed together with a secret that's valid for 12 hours. This should in theory offer some protection against reversing it.
The new identifier is also used in the existing throttle cache.
=> Store visitor identifiers on recording view

app/assets/javascripts/jquery.bxslider.js, app/assets/stylesheets/frontend/shared/_promoted.scss, app/assets/stylesheets/jquery.bxslider.css.scss
When analyzing the problem with the long titles I noticed there are new version of the slider available containing some bugfixes: https://github.com/stevenwanderski/bxslider-4#changelog
I noticed jquery.bxslider.css.scss seemed to have been manually changed for the image paths. I did these changes as well but had to change ``asset-url("images/bxslider/bx_loader.gif")`` to ``asset-url("bxslider/bx_loader.gif")`` in order to generate a working image path.
The location of the file did not change. ``http://media.ccc.vm:3000/assets/bxslider/bx_loader-6d46e2cf165a5a0584afba7bc9663da292ee08c97cfc7613de6013ed05be892a.gif`` is generated in the development environment.
Currently production uses the following URL which responds with 204 (no content) https://media.ccc.de/images/bxslider/bx_loader.gif …
=> Upgraded bxslider from 4.1.2 to 4.2.5

app/models/frontend/event.rb, app/views/frontend/shared/_promoted.haml, test/models/frontend/event_test.rb
Shortened event titles for the promotion slider to prevent the text reaching into the slider controls.
Tested in ff, chrome, android
Before:
After:
=> Shortened event titles for the promotion slider

app/views/frontend/home/index.html.haml
In my opinion the text "_14.215 files in 3.668 videos at 99 conferences_" could be improved, since I am already associating "file" with "video" and doesn't make much sense.
Since there are not only files from conferences but also theaters or blinkenlights available I am suggesting the following:
_14.170 files of 3.661 recordings at 98 events_
The term event is already used on the start page on the button "all events" and is therefore something the user already knows.
_I am aware, that the term recording and event is used differently in the model but I think that should not be something the user has to experience and we should use words a normal user would use._
=> Rewording of the statistics claim. videos -> recordings, conferences -> events

app/assets/stylesheets/frontend/pages/_show.scss
See #209. It was missing the "float: left" property when it wasn't part of a subtitle dropdown box.
=> Fix positioning of "Download subtitle" button

app/views/frontend/home/index.html.haml
Commas as well as dots have the potential to confuse people.
=> Use thin spaces as a decimal delimiter, as suggested by ISO 31-0

app/controllers/frontend/conferences_controller.rb, app/views/frontend/conferences/show.html.haml, app/views/frontend/shared/_event_metadata.haml
See #196. Here's my rationale for putting the attributes in the order "date - view_count - people": The eye icons line up, and you can compare the numbers more easily. If you put the view count last, there's more visual noise.
=> Allow the conference view to be sorted by view count

.gitignore, app/assets/stylesheets/frontend/pages/_show.scss, app/helpers/frontend/application_helper.rb, app/models/frontend/event.rb, app/views/frontend/events/show.html.haml, app/views/frontend/home/index.html.haml
Fixing #235
you could argue about sorting of the most recent conferences list on the main page. It would now obey the event date too.
Any comments on that? (FYI @derpeter)
After this would be deployed we could update the conference last released date using a "batch job".
One could argue we should refactor the "event_last_released_at" column. Any comments on that, is it worth it?
=> #235 Use event date instead of publish date for display and recent event list

app/views/frontend/home/about.haml
Hey there,
It was a little disapointing to see that there was an Apple TV but no Android TV App, so I built one in my spare time. I would appreciate a mentioning on the listed Apps section on the about page ;)
=> adds Android TV App to apps section on about page

app/controllers/frontend/conferences_controller.rb
This should make it easier for people to find talks deemed popular by other users, highlighting quality content.
In a quick user study, I found that nobody ever noticed/knew about the top menu with different sorting options.
=> Sort the conference view by "view count" by default

app/assets/stylesheets/frontend/shared/_promoted.scss, app/models/frontend/conference.rb, app/views/frontend/shared/_live.html.haml
=> Live stream promotion styling

app/views/frontend/shared/_download.haml
they were only displayed for audio-releases, for which we actually don't so multi-language releases, so they just cluttered the ui with useless information
=> remove useless language-icons

Vagrantfile
This replaces the Google public DNS server with dnscache.berlin.ccc.de (213.73.91.35), a public DNS server provided by the Berlin CCC group. I personally found this to be very reliable. For more information, see e.g,. https://www.ccc.de/de/censorship/dns-howto.
=> Use privacy aware DNS server instead of Google's for Vagrant

app/views/public/shared/_conference.json.jbuilder, app/views/public/shared/_event.json.jbuilder, app/views/public/shared/_recording.json.jbuilder
Having database IDs in some places, but not supporting them throughout
the API is confusing.
* add slug to related events metadata, remove id in a later commit
* generated urls use guid for events
* generated urls use acronym for conferences
* recordings still use database ID
=> Remove database ID from public JSON URLs

README.md, app/admin/event.rb, app/assets/javascripts/activate-timelens.js, app/assets/javascripts/application.js, app/assets/javascripts/oembed-player.js, app/assets/stylesheets/application.css, app/assets/stylesheets/embed.css.scss, app/assets/stylesheets/timelens-custom.css, app/controllers/api/events_controller.rb, app/models/event.rb, app/models/frontend/event.rb, app/views/frontend/shared/_event_metadata.haml, app/views/frontend/shared/_player_video.haml, app/views/public/shared/_event.json.jbuilder, db/migrate/20180914181622_add_timelens_to_event.rb, db/schema.rb, test/controllers/api/events_controller_test.rb, test/factories.rb, test/integration/events_api_test.rb, test/models/event_test.rb, vendor/assets/javascripts/timelens.js, vendor/assets/stylesheets/timelens.css
This adds support for displaying visual timelines and popup thumbnails
throughout voctoweb's interface, aiming to make video navigation more
efficient, precise, and active. See <https://timelens.io> for an explanation of
what this is all about.
Two fields, "timeline_filename" and "thumbnails_filename" are added to
the Event model. When present, the Timelens plugin for MediaElement.js
is activated. Also, Timelens interfaces are added to video listings.
When the Timelens fields are not filled, everything works as before.
=> Add Timelens support, to improve video navigation capabilities

app/models/recording.rb
Some contributors use subdirectories named by year for their uploads; with those slides weren't correctly detected as the directory name didn't start with `slides` but rather with e.g. `2018/slides`. This patch changes the behavior so that the string `slides` can be anywhere in the path and doesn't need to be at the beginning.
=> Support slides subdirectories

app/models/frontend/event.rb
#first does not accept a block, which results in this function always
returning the first relive recording, rather than a matching one. Use
#find instead.
=> correctly match event to relive recording

app/views/frontend/home/about.haml
all mirrors of [https://media.ccc.de/about.html#status](https://media.ccc.de/about.html#status) serve files over https, so the hint can be removed.
=> remove hint files will be served over http

app/controllers/public/events_controller.rb, app/controllers/public/recordings_controller.rb, app/models/event.rb, app/views/public/shared/_event.json.jbuilder, test/models/event_test.rb
This pull request should greatly reduce the amount of SQL queries needed for requests to the public API. It does not change API response behavior.
Furthermore, it adds the capability to request events by their slug, e.g. `/public/events/dg-82` now returns the same information as `/public/events/70d63b5d-0e39-4271-b4e5-fefc783b2a2b`.
=> Public API: Speed improvements

README.md
The RVM people have added a new person that signs their binaries, and the verify line was missing the binary on the command line.
=> fix GPG keys for RVM

vendor/assets/javascripts/timelens.js
The current timelens version generates VTT files with timestamps that
have an hour position instead of using minute values > 60. The version
of timelens.js used in voctoweb does not handle this, causing the
thumbnails of the first minutes to stretch over the entire video.
Fix this by importing the patch proposed in an upstream PR[1].
[1] https://github.com/timelens/timelens.js/pull/3
=> player: fix timelens VTT parsing

app/controllers/frontend/popular_controller.rb, app/views/frontend/popular/index.haml, config/routes.rb
This commit enhances the "Popular Events" page in two ways:
- Allow to limit the shown events by year of the event  #388
- Allow to browse through multiple pages #336 
This should also solve #207.
Since this is the first time I commit to a ruby-on-rails project I don't expect the PR to be finished already, but would like to get some feedback, including:
- Are we nerdy enough to start counting the pages at zero or should I switch to "fortran style"?
- How bad are my SQL Queries?
- Is the "design" sophisticated enough?
- What else needs to be fixed to get this merged and deployed?
=> Add subpages to 'Events' to filter by year

Dockerfile, docker-compose.yml, docker/database.yml
The alpine switch should significantly reduce the size of to-be-downloaded container images, thus make it easier to set up the development environment.
I am not sure about the use-case of an SSH server within the development setup, thus I removed it. Shouldn't it be sufficient to just use `docker-compose run`?
Additional changes:
+ Bump docker-compose file version to 3
+ The official postgres docker image now requires a password to be set
+ Set fixed version numbers for docker containers to prevent incompatibilities
+ Some reformatting and simplification
=> Switch docker setup to alpine + some housekeeping

app/assets/stylesheets/timelens-custom.css
The problem was that Timelens' CSS changes on the Clappr player are always applied, even if the Clappr player is used to display relive content.
This is a fast fix for the problem. I described how to solve this in a more general way in the place where the fix is applied: We would need to set it up in a way so that timelens.css is only loaded for pages with a Clappr player where a visual timeline is desired.
Fixes #420 :herb:
=> Undo Timelens styles for Clappr players inside of relive-player classes.

app/controllers/frontend/search_controller.rb, app/models/concerns/elasticsearch_event.rb, app/models/conference.rb, app/models/event.rb, app/models/frontend/conference.rb, app/models/frontend/recording.rb, app/models/recording.rb, app/views/frontend/search/index.html.haml, docker-compose.yml, elasticsearch.yml
This PR fixes some issues with the search query and prepares the index for the requirements outlined in #444 and #289 
* full match on titles are now weighted higher, and weighted average instead of multiply in decay function is used, so searches for the exact title of a talk e.g. "we lost the war" always yield the hopefully correct results.
For the long term we also should add some "post-integration" tests for the full content elastic index, so we can actually compare changes to the es query – @robinkaranu said he will look into that in the next weeks...
=> Improve search

app/views/frontend/home/about.haml
The namespace of the youtube-dl GitHub repo has been changed.
=> Update youtube-dl URL in app/views/frontend/home/about.haml

app/views/frontend/home/about.haml
The addon URL changed and is now different for different Kodi versions, so It's probably better to just link the GitHub repository...
=> Switch Kodi URL to GitHub repository

app/views/layouts/frontend/frontend.html.haml, config/locales/custom.en.yml
This PR inverts the order of the components in the page title. Currently, the page title always begins with the static part `media.ccc.de` and then shows the dynamic part, i.e. the selected conference/event. This PR puts the dynamic part first and the static part second.
Fixes #723
=> Invert order of title components

Dockerfile
bin/update-data curls the fixtures tgz. if curl is not present in the container, it fails.
=> add curl to make update-data not break

config/deploy.rb, config/environments/production.rb
Failed to deploy on production with:
Uglifier::Error:
../gems/uglifier-4.2.0/lib/uglifier.rb:291:in `parse_result'
See lautis/uglifier/issues/185
=> Specify uglifier as symbol instead

app/views/frontend/home/about.haml
The old webirc service is being replace by chat.hackint.org.
=> Update hackint webchat URL

app/helpers/frontend/event_recording_filter.rb, db/migrate/20250120233533_add_translated_to_recordings.rb, db/schema.rb
For now, guessing the value from the folder.
Detects 'opus-translation' and 'mp3-translated'.
=> Add translated flag to recordings, skip in RSS

README.md, bin/docker-dev-up
`compose` is for some time now being called with [`docker compose`](https://docs.docker.com/reference/cli/docker/compose/) and not `docker-compose`. This PR changes all the docker commands and references in the README.md. Since multiple calls of `bin/docker-dev-up` left me with dangling containers I added the `--remove-orphans` to clean up the unused containers.
=> Changes legacy docker-compose to current docker compose command
